### ISSUE TITLE
Enhancement: Support for other CSS styles with easy switching

### ISSUE THREAD

**Issue by dumblob** [euclio/aurelius#1]
Are there any plans to add few other CSS styles resembling other common outputs (especially LaTeX/PDF like [paper-looking CSS](https://github.com/bgw/pan-am) or [Scholarly](http://scholarlymarkdown.com/) [Markdown](https://github.com/timtylin/scholdoc-examples) [CSS](http://scholarlymarkdown.com/scholdoc-distribution/css/core/scholmd-core-latest.css)) and a tiny disappearing-without-mouse-movement drop-down list to choose one right on the preview page?

This would be a killer-feature, because with https://github.com/Kozea/WeasyPrint or similar converter, it would be easy to produce high-quality professional documents (including academic papers, thesis, documentation etc.).

**Comment by euclio** [comment]
I've been thinking about this, and I definitely think it would be a good idea.
