### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by maximbaz** [euclio/aurelius#10]
Hi @euclio, could you please update dependencies in [static/vendor](https://github.com/euclio/aurelius/tree/master/static/vendor) folder? I noticed [this issue](https://github.com/euclio/vim-markdown-composer/issues/51) first, but then I also noticed that github-markdown-css is also very very old.

**Comment by maximbaz** [comment]
I wonder if it is possible somehow to link to the latest available vendor dependencies, instead of a particular commit that you have to constantly keep updating? For example, [github-markdown-css](https://github.com/sindresorhus/github-markdown-css/releases) publishes new releases every few months, it is a pity that users can't update the dependency without your help.

**Comment by euclio** [comment]
Yes, hopefully I can get around to https://github.com/euclio/aurelius/issues/1 soon, which would allow people to set their own styles.
