### ISSUE TITLE
aurelius::Server freeze when sending "<a"

### ISSUE THREAD

**Issue by Tosainu** [euclio/aurelius#20]
`aurelius::Server` freeze when sending `<a`.

**To Reproduce**

Run the following code. This program will freeze after printing `listening on [::1]:xxxx`.

```rust
use aurelius::Server;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut server = Server::bind("localhost:0")?;

    println!("listening on {}", server.addr());

    server.send("<a".to_owned())?;

    Ok(())
}
```

**Environment**

- Arch Linux
- rustc 1.45.2 (d3fb005a3 2020-07-31)
- aurelius 0.7.2 and 07d861388f4185047ba52456a3ab717a1648564a

**Comment by euclio** [comment]
Thanks for the report!
