### ISSUE TITLE
provide simple usage examples for beginners

### ISSUE THREAD

**Issue by alexzanderr** [euclio/aurelius#27]
hello

i've looked everywhere, even in the vim plugin. its hard to understand how to make a simple example of the server running inside a working directory and rendering a folder of markdown files.

please provide some simple example usages in the readme of how to use the server.

i just want to make a simple application that uses this server to render markdown files from my projects.

**Comment by alexzanderr** [comment]
ok so from what i've seen the vim plugin you can create a minimal example like this

```rust
	let mut server = Server::bind(format!(
        "{}:{}",
	    matches.value_of("address").unwrap_or("localhost"),
        matches.value_of("port").unwrap_or("0")
    ))?;

    if let Some(external_renderer) = matches.value_of("external-renderer")
    {
        server.set_external_renderer(parse_command(external_renderer));
    }

    if let Some(highlight_theme) = matches.value_of("theme") {
        server.set_highlight_theme(highlight_theme.to_string());
    }

    if let Some(working_directory) = matches.value_of("working-directory")
    {
        server.set_static_root(working_directory);
    }

    if let Some(custom_css) = matches.values_of("css") {
        server.set_custom_css(custom_css.map(String::from).collect())?;
    }

    if let Some(file_name) = matches.value_of("markdown-file") {
        server.send(fs::read_to_string(file_name)?)?;
    }

    let browser = matches.value_of("browser");

    if !matches.is_present("no-auto-open") {
        if let Some(browser) = browser {
            server.open_specific_browser(parse_command(browser))?;
        } else {
            server.open_browser()?;
        };
    }
	
	// then you can load a markdown from disk
    let markdown = include_str!("../README.md");
    
    // here its a simple example
    // this code sends line by line the markdown to the server after one second; 
    // just to test if its working and to simulate a real world example
    println!("awaiting ...");
    let mut lines = markdown.split("\n");
    let mut total = String::from("");
    while let Some(line) = lines.next() {
        total.push_str(line);
        total.push_str("\n");
        server.send(total.clone());
        std::thread::sleep_ms(1000);
    }

```
this part is taken from `main.rs` from the vim plugin

`server.send(String)` does all the work; it parses markdown to html and sends it to the browser to load the rendered page

in the vim plugin the stdin of the server its locked so that vim can spawn the server process as child an send data to it
```rust
    let stdin = io::stdin();
    let stdin_lock = stdin.lock();

    read_rpc(stdin_lock, server, browser)?;
```
proof in the vim script
```vim
  if has('nvim')
    let l:job = jobstart(l:args, {
          \ 'cwd': s:plugin_root,
          \ 'rpc': v:true,
          \ 'on_exit': function('s:onServerExit'),
          \ })
    if l:job == -1
      echom 'Could not execute markdown composer: try ' .
            \ '`cargo build --release` in the plugin directory'
      return
    endif
    let s:job = l:job
  else
```
`l:args` contains the binary path

now, you dont need to do that, you can start the server and just `send` data to it with `.send()` method

**Comment by alexzanderr** [comment]
but still i would like beginner example usages int the readme, for all the people.

**Comment by euclio** [comment]
Thanks for opening an issue. I prefer to put examples in the documentation instead of the README.

There's a simple usage example in the documentation here: https://docs.rs/aurelius/latest/aurelius/#example

There's also more documentation on the `Server` struct: https://docs.rs/aurelius/latest/aurelius/struct.Server.html

You can also take a look at the integration tests for more examples.

**Comment by alexzanderr** [comment]
thanks for response!
